spring:
  application:
    name: crud

  datasource:
    url: jdbc:mariadb://localhost:3306/banco_prova
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false  # Desabilitado, já que você está usando MariaDB